---
# tasks file for Rproxy

- name: update-ing yum
  yum: name=* state=latest
  tags:
     - packageupdate

- name: checking command setenforce 0
  command: setenforce 0
  tags:
     - doingsent

# Disable SELinux
- selinux:
    state: disabled

- name: Download epel from site
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /root/

- name: Install epel package.
  yum:
     name: /root/epel-release-latest-7.noarch.rpm
     state: present

- name: Download remi repositry from site
  get_url:
    url: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    dest: /root/

- name: Install remi package.
  yum:
     name: /root/remi-release-7.rpm
     state: present

- name: update-ing yum
  yum: name=* state=latest

- name: install the latest version of wget
  yum:
    name: wget
    state: latest

